# Generated by Django 5.0.6 on 2026-06-25 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['campaign', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MetricSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('API', 'API'), ('MANUAL', 'Ручной ввод'), ('IMPORT', 'Импорт')], default='MANUAL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MetricType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('unit', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('entity_type', models.CharField(choices=[('campaign', 'Кампания'), ('activity', 'Активность')], max_length=20)),
            ],
            options={
                'ordering': ['entity_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('manager', 'Менеджер'), ('executor', 'Исполнитель'), ('head', 'Руководитель')], default='manager', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_url', models.URLField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='core.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('goal', models.TextField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.campaign'),
        ),
        migrations.AddField(
            model_name='activity',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='core.channel'),
        ),
        migrations.AddField(
            model_name='activity',
            name='metric_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='core.metricsource'),
        ),
        migrations.CreateModel(
            name='MetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('collected_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_values', to='core.activity')),
                ('metric_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='core.metrictype')),
            ],
            options={
                'ordering': ['activity', 'metric_type'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(blank=True, max_length=255)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.campaign')),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='status',
            constraint=models.UniqueConstraint(fields=('name', 'entity_type'), name='unique_status_for_entity'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.ForeignKey(limit_choices_to={'entity_type': 'campaign'}, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='core.status'),
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.ForeignKey(limit_choices_to={'entity_type': 'activity'}, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='core.status'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='metricvalue',
            constraint=models.UniqueConstraint(fields=('activity', 'metric_type'), name='unique_metric_for_activity'),
        ),
    ]
